version: '3.1'

services:
  web:
    container_name: ${PROJECT_NAME}
    image: wordpress:${WP_BUILD_VERSION}-php${PHP_IMAGE}
    build:
      args:
        WP_BUILD_VERSION: ${WP_BUILD_VERSION}
        WP_BUILD_SHA1: ${WP_BUILD_SHA1}
        PHP_IMAGE: php:${PHP_IMAGE}
      context: ./docker-wp-files
    restart: unless-stopped
    ports:
      - ${EXPOSE_PORTS}
    environment:
      WORDPRESS_DB_HOST: host.docker.internal
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    working_dir: /var/www/html
    volumes:
      - ./site:/var/www/html
      - ./php-files/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    extra_hosts:
      - host.docker.internal:host-gateway