version: '3.1'

services:
  web:
    container_name: Wordpress
    image: wordpress:6.2.2-php7.4-apache  
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: admin
      WORDPRESS_DB_PASSWORD: 1234qwer
      WORDPRESS_DB_NAME: wordpress
    working_dir: /var/www/html
    volumes:
      - ./site:/var/www/html
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: mysql:5.7.42
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234qwer
      MYSQL_RANDOM_ROOT_PASSWORD: 1234qwer
    volumes:
      - db:/var/lib/mysql

volumes:
  db: